### ISSUE TITLE
Humbug giving negative drops?

### ISSUE THREAD

**Issue by Colonization** [erocs/Humbug#73]
Whenever we kill a mob on our server, it drop items with a negative. Also, is it possible to enable certain drops for some mobs, but not others? this includes XP drops.

Edit: Should of probably posted this on Civcraft/Humbug, but the build.civcraft.co site leads here.

http://i.imgur.com/ffMYTkd.png

**Comment by erocs** [comment]
This repo is an old version. Are you using https://github.com/Civcraft or a build from http://build.civcraft.co/job/Humbug-master?

**Comment by Colonization** [comment]
I'm using the latest version from http://build.civcraft.co/job/Humbug-master/. I meant to post to the Civcraft humbug github, but accidentally posted it on yours. My apologies.

**Comment by erocs** [comment]
No worries. What is your loot_multiplier settings in your conifg?

**Comment by Colonization** [comment]
Strange, it was set to -1. I hadn't changed anything, but I changed it to 1 and it seems to have fixed the problem, I appreciate the help erocs!

If you don't mind, I have one last question, how do you configure the remove_mob_drops? anytime I try, it just says," 24.12 11:10:38 [Server] INFO remove_mob_drops = " and nothing else.

**Comment by erocs** [comment]
humbug remove_mob_drops add IRON_INGOT
humbug save


humbug remove_mob_drops del IRON_INGOT
humbug save
